using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2005 Atlone.")]
[assembly: AssemblyCompanyAttribute("LogSpy")]
[assembly: AssemblyProductAttribute("LogSpy")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]

